const Home_product =
[
  {
    id:1,
    Name: 'product1',
    price: '276',
    imgs: 'imgs/p1.webp',
    cat: 'tv',
    type: 'new',
  },
  {
    id: 2,
    Name: 'product2',
    price: '206',
    imgs: 'imgs/p2.webp',
    cat: 'laptop',
    type: 'new',
  },
  {
    id:3,
    Name: 'product3',
    price: '266',
    imgs: 'imgs/p3.webp',
    cat: 'watch',
    type: 'new',
  },
  {
    id:4,
    Name: 'product4',
    price: '260',
    imgs: 'imgs/p9.jpg',
    cat: 'laptop',
    type: 'new',
  },
  {
    id:5,
    Name: 'product5',
    price: '100',
    imgs: 'imgs/p4.webp',
    cat: 'speaker',
    type: 'Featured',
  },
  {
    id:6,
    Name: 'product6',
    price: '112',
    imgs: 'imgs/p5.webp',
    cat: 'electronics',
    type: 'Featured',
  },
  {
    id:7,
    Name: 'product7',
    price: '236',
    imgs: 'imgs/p10.jpg',
    cat: 'headphone',
    type: 'Featured',
  },
  {
    id:8,
    Name: 'product8',
    price: '326',
    imgs: 'imgs/p11.jpg',
    cat: 'electronics',
    type: 'Featured',
  },
  {
    id:9,
    Name: 'product9',
    price: '346',
    imgs: 'imgs/p6.webp',
    cat: 'phone',
    type: 'top',
  },
  {
    id:10,
    Name: 'product10',
    price: '336',
    imgs: 'imgs/p7.webp',
    cat: 'speaker',
    type: 'top',
  },
  {
    id:11,
    Name: 'product11',
    price: '360',
    imgs: 'imgs/p8.webp',
    cat: 'speaker',
    type: 'top',
  },
  {
    id:12,
    Name: 'product12',
    price: '3386',
    imgs: 'imgs/p3.webp',
    cat: 'speaker',
    type: 'top',
  },
]

export default Home_product;