const Products =

[

    {
        id:1,
        Name: 'product1',
        price: '276',
        imgs: 'imgs/t1 (2).jpg',
        cat: 'tv',
        type: 'new',
      },
      {
        id: 2,
        Name: 'product2',
        price: '306',
        imgs: 'imgs/t2.jpg',
        cat: 'tv',
        type: 'new',
      },
      {
        id:3,
        Name: 'product3',
        price: '466',
        imgs: 'imgs/t8.jpg',
        cat: 'tv',
        type: 'new',
      },
      {
        id:4,
        Name: 'product4',
        price: '766',
        imgs: 'imgs/t3.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:5,
        Name: 'product5',
        price: '866',
        imgs: 'imgs/t9.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:6,
        Name: 'product6',
        price: '246',
        imgs: 'imgs/m1.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:7,
        Name: 'product7',
        price: '866',
        imgs: 'imgs/t11.jpg',
        cat: 'speaker',
        type: 'new',
      },
      {
        id:8,
        Name: 'product8',
        price: '966',
        imgs: 'imgs/t7.jpg',
        cat: 'speaker',
        type: 'new',
      },
      {
        id:9,
        Name: 'product9',
        price: '256',
        imgs: 'imgs/v5.jpg',
        cat: 'speaker',
        type: 'new',
      },
      {
        id:10,
        Name: 'product10',
        price: '966',
        imgs: 'imgs/t13.jpg',
        cat: 'electronics',
        type: 'new',
      },
      {
        id:11,
        Name: 'product11',
        price: '288',
        imgs: 'imgs/v6.jpg',
        cat: 'electronics',
        type: 'new',
      },
      {
        id:12,
        Name: 'product12',
        price: '206',
        imgs: 'imgs/v8.jpg',
        cat: 'electronics',
        type: 'new',
      },
      {
        id:13,
        Name: 'product13',
        price: '226',
        imgs: 'imgs/v13.jpg',
        cat: 'phone',
        type: 'new',
      },
      {
        id:14,
        Name: 'product14',
        price: '666',
        imgs: 'imgs/t17.jpg',
        cat: 'phone',
        type: 'new',
      },
      {
        id:15,
        Name: 'product15',
        price: '766',
        imgs: 'imgs/t18.jpg',
        cat: 'phone',
        type: 'new',
      },
      {
        id:16,
        Name: 'product16',
        price: '886',
        imgs: 'imgs/t20.jpg',
        cat: 'phone',
        type: 'new',
      },
      {
        id:17,
        Name: 'product17',
        price: '888',
        imgs: 'imgs/v19.jpg',
        cat: 'laptop',
        type: 'new',
      },
      {
        id:18,
        Name: 'product18',
        price: '999',
        imgs: 'imgs/v17.jpg',
        cat: 'laptop',
        type: 'new',
      },
      {
        id:19,
        Name: 'product19',
        price: '555',
        imgs: 'imgs/v2.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:20,
        Name: 'product20',
        price: '436',
        imgs: 'imgs/t23.jpg',
        cat: 'tv',
        type: 'new',
      },
      {
        id:21,
        Name: 'product21',
        price: '256',
        imgs: 'imgs/n6.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:22,
        Name: 'product22',
        price: '777',
        imgs: 'imgs/p1.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:23,
        Name: 'product23',
        price: '737',
        imgs: 'imgs/p2.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:24,
        Name: 'product24',
        price: '966',
        imgs: 'imgs/p3.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:25,
        Name: 'product25',
        price: '897',
        imgs: 'imgs/p4.jpg',
        cat: 'Airpods',
        type: 'new',
      },
      {
        id:26,
        Name: 'product26',
        price: '152',
        imgs: 'imgs/p5.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:27,
        Name: 'product27',
        price: '266',
        imgs: 'imgs/v16.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:28,
        Name: 'product28',
        price: '426',
        imgs: 'imgs/n9.jpg',
        cat: 'Bag',
        type: 'new',
      },
      {
        id:29,
        Name: 'product29',
        price: '646',
        imgs: 'imgs/n10.jpg',
        cat: 'laptop',
        type: 'new',
      },
      {
        id:30,
        Name: 'product30',
        price: '796',
        imgs: 'imgs/n13.jpg',
        cat: 'laptop',
        type: 'new',
      },
]
export default Products;